### ISSUE TITLE
数据集似乎有点问题

### ISSUE THREAD

**Issue by zhaxc11** [ymaoj/Tibetan-LLAMA2-Tibetan-Alpaca#1]
”གཉའ་ཁྲི་བཙན་པོའི་ཡབ་གནམ་རི་སྲོང་བཙན། “？？？

**Comment by ymaoj** [comment]
您好，本项目训练数据集没有问题，只是在算力和数据规模受限的情况下，相关模型的训练并不充分，虽然具有一定的藏文理解及生成能力，但生成结果的准确性还需进一步提升。
