### ISSUE TITLE
请问结果不能复现?

### ISSUE THREAD

**Issue by liufeifeifei** [ymaoj/Tibetan-LLAMA2-Tibetan-Alpaca#4]
在Tibetan-Alpaca-7B上按照例子，结果是藏文很多都是直接输出问题，英文和中文都是输出一个很乱的东西。

**Comment by insogao** [comment]
我试了也是这样的。藏语进藏语出，但是我的提示词是translate to english

**Comment by ymaoj** [comment]
您好，我们的模型是在纯藏文数据上进行增量预训练和指令微调的，Tibetan-Alpaca-7B在藏文的开放问答、摘要生成、新闻生成、释义生成、时态生成以及文本分类任务上具备较好的生成能力，但不具备英文和中文的生成能力。由于指令微调时也未加入翻译数据进行训练模型，所以更不具备翻译功能，望理解。对于结果不能复现这个问题，如果说的是“模型生成示例”中的截图，那么，多次输入同一个问题，大模型生成内容有些时候会一样，多数时候会不一样的，建议多次尝试。
